"""empty message

Revision ID: 9a115adeb654
Revises: 20662f462c27
Create Date: 2020-05-07 16:26:06.739009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a115adeb654'
down_revision = '20662f462c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('remouteImage', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('film', 'remouteImage')
    # ### end Alembic commands ###
